### ISSUE TITLE
Feature Addition? Pause Button

### ISSUE THREAD

**Issue by Nevicar** [Ivanobix/ToxicFishing#1]
Heyo,

Great update to an already great program. This fixes a ton of issues that I was having, however I'm running into something that's somewhat undesirable. I'm not sure if it's a problem with Windows 11 and the new Terminal, but previously when I ran the command shell version of this program I could click somewhere in the CMD window and it'd basically pause the program until I cleared the selection. This behavior does not happen in (the most recent version of) Windows 11, and thus, it runs endlessly, forcing me to completely close the window should I have to move.

Is there an easy way to slap in some code somewhere that allows us to set a key to basically pause the process until it's triggered again? I have 0 experience writing C#.

If it's too much an ask, obviously, just ignore.

Thanks!

**Comment by Ivanobix** [comment]
Hello!

First of all, I'm very sorry for the delay in responding to this issue. For some reason, GitHub did not notify me about its creation.

Thank you very much for your positive feedback and for your valuable collaboration in pointing out the problem you are experiencing with Windows 11. I fully understand the situation you are describing and I think it is an excellent suggestion to add the possibility to pause the process with a specific key.

I will get to work with this request and I hope to be able to upload a new release soon with this feature you have requested. Thank you for your patience and understanding!

Greetings and again, thanks for your input!

**Comment by Ivanobix** [comment]
Hello! @Nevicar 

First of all, I'm very sorry for the delay in responding to this issue. For some reason, GitHub did not notify me about its creation.

Thank you very much for your positive feedback and for your valuable collaboration in pointing out the problem you are experiencing with Windows 11. I fully understand the situation you are describing and I think it is an excellent suggestion to add the possibility to pause the process with a specific key.

I will get to work with this request and I hope to be able to upload a new release soon with this feature you have requested. Thank you for your patience and understanding!

Greetings and again, thanks for your input!

Translated with www.DeepL.com/Translator (free version)

**Comment by Ivanobix** [comment]
Hello! @Nevicar 

First of all, I'm very sorry for the delay in responding to this issue. For some reason, GitHub did not notify me about its creation.

Thank you very much for your positive feedback and for your valuable collaboration in pointing out the problem you are experiencing with Windows 11. I fully understand the situation you are describing and I think it is an excellent suggestion to add the possibility to pause the process with a specific key.

I will get to work with this request and I hope to be able to upload a new release soon with this feature you have requested. Thank you for your patience and understanding!

Greetings and again, thanks for your input!

**Comment by Ivanobix** [comment]
Hello! @Nevicar .

After reviewing the situation you mentioned, I've decided to introduce the option to set a timer during the app's execution. This way, you can let the bot run for a specified number of hours/minutes, and it will automatically stop if you wish. Additionally, I've enhanced the graphics, fixed the fishing in lava issue, reduced the amount of generated logs, and now, when the application stops, it displays basic statistics about the fishing session.

While this might not be the exact functionality you requested, I believe this approach adds more value to the software and aligns better with this type of tool. If you have any other suggestions or issues, I'd be more than happy to assist you.

Best regards.
